routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Backend\TagController;
use App\Http\Controllers\Backend\CategoryController;
use App\Http\Controllers\Backend\SubcategoryController;
use App\Http\Controllers\Backend\RoleController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Backend\ModuleController;
use App\Http\Controllers\Backend\ProductController;
use App\Http\Controllers\Backend\AttributeController;
use App\Http\Controllers\Backend\PermissionController;
use App\Http\Controllers\Backend\SettingController;
use App\Http\Controllers\Backend\BrandController;
    use App\Http\Controllers\Backend\SliderController;

Route::get('/', [\App\Http\Controllers\Frontend\FrontController::class, 'index'])->name('frontend.front.index');

Auth::routes();

Route::get('/home', [App\Http\Controllers\DashboardController::class, 'index'])->name('home');
Route::get('/table', [App\Http\Controllers\DashboardController::class, 'table'])->name('table');
Route::get('/form', [App\Http\Controllers\DashboardController::class, 'form'])->name('form');

Route::prefix('backend')->name('backend.')->middleware('auth')->group(function () {
    Route::get('/tag/trash', [TagController::class, 'trash'])->name('tag.trash');
    Route::get('/tag/restore/{id}', [TagController::class, 'restore'])->name('tag.restore');
    Route::delete('/tag/force-delete/{id}', [TagController::class, 'forceDelete'])->name('tag.force_delete');

    Route::resource('tag', TagController::class);
});

Route::prefix('backend')->name('backend.')->middleware(['auth','permission'])->group(function () {
    Route::get('/category/trash', [CategoryController::class, 'trash'])->name('category.trash');
    Route::get('/category/restore/{id}', [CategoryController::class, 'restore'])->name('category.restore');
    Route::delete('/category/force-delete/{id}', [CategoryController::class, 'forceDelete'])->name('category.force_delete');
    Route::post('/category/get_subcategory', [CategoryController::class, 'getSubcategory'])->name('category.get_subcategory');

    Route::resource('category', CategoryController::class);
});

Route::prefix('backend')->name('backend.')->middleware('auth')->group(function () {
    Route::get('/subcategory/trash', [SubcategoryController::class, 'trash'])->name('subcategory.trash');
    Route::get('/subcategory/restore/{id}', [SubcategoryController::class, 'restore'])->name('subcategory.restore');
    Route::delete('/subcategory/force-delete/{id}', [SubcategoryController::class, 'forceDelete'])->name('subcategory.force_delete');

    Route::resource('subcategory', SubcategoryController::class);
});


Route::prefix('backend')->name('backend.')->middleware(['auth','permission'])->group(function () {
    Route::get('/role/trash', [RoleController::class, 'trash'])->name('role.trash');
    Route::get('/role/restore/{id}', [RoleController::class, 'restore'])->name('role.restore');
    Route::delete('/role/force-delete/{id}', [RoleController::class, 'forceDelete'])->name('role.force_delete');
    Route::get('/role/assign_permission_form/{id}', [RoleController::class, 'assignPermissionForm'])->name('role.assign_permission_form');
    Route::post('/role/assign_permission/{id}', [RoleController::class, 'assignPermission'])->name('role.assign_permission');

    Route::resource('role', RoleController::class);
});


Route::prefix('backend')->name('backend.')->middleware('auth')->group(function () {
    Route::get('/user/trash', [UserController::class, 'trash'])->name('user.trash');
    Route::get('/user/restore/{id}', [UserController::class, 'restore'])->name('user.restore');
    Route::delete('/user/force-delete/{id}', [UserController::class, 'forceDelete'])->name('user.force_delete');

    Route::resource('user', UserController::class);
});


Route::prefix('backend')->name('backend.')->middleware('auth')->group(function () {
    Route::get('/module/trash', [ModuleController::class, 'trash'])->name('module.trash');
    Route::get('/module/restore/{id}', [ModuleController::class, 'restore'])->name('module.restore');
    Route::delete('/module/force-delete/{id}', [ModuleController::class, 'forceDelete'])->name('module.force_delete');
    Route::resource('module', ModuleController::class);
});

Route::prefix('backend')->name('backend.')->middleware(['auth','permission'])->group(function () {
    Route::get('/product/trash', [ProductController::class, 'trash'])->name('product.trash');
    Route::get('/product/restore/{id}', [ProductController::class, 'restore'])->name('product.restore');
    Route::delete('/product/force-delete/{id}', [ProductController::class, 'forceDelete'])->name('product.force_delete');
    Route::resource('product', ProductController::class);
});


Route::prefix('backend')->name('backend.')->middleware('auth')->group(function () {
    Route::get('/attribute/trash', [AttributeController::class, 'trash'])->name('attribute.trash');
    Route::get('/attribute/restore/{id}', [AttributeController::class, 'restore'])->name('attribute.restore');
    Route::delete('/attribute/force-delete/{id}', [AttributeController::class, 'forceDelete'])->name('attribute.force_delete');
    Route::resource('attribute', AttributeController::class);
});

Route::prefix('backend')->name('backend.')->middleware('auth')->group(function () {
    Route::get('/permission/trash', [PermissionController::class, 'trash'])->name('permission.trash');
    Route::get('/permission/restore/{id}', [PermissionController::class, 'restore'])->name('permission.restore');
    Route::delete('/permission/force-delete/{id}', [PermissionController::class, 'forceDelete'])->name('permission.force_delete');
    Route::resource('permission', PermissionController::class);
});

Route::prefix('backend')->name('backend.')->middleware('auth')->group(function () {
    Route::get('/setting/trash', [SettingController::class, 'trash'])->name('setting.trash');
    Route::get('/setting/restore/{id}', [SettingController::class, 'restore'])->name('setting.restore');
    Route::delete('/setting/force-delete/{id}', [SettingController::class, 'forceDelete'])->name('setting.force_delete');
    Route::resource('setting', SettingController::class);
});

Route::prefix('backend')->name('backend.')->middleware('auth')->group(function () {
    Route::get('/brand/trash', [BrandController::class, 'trash'])->name('brand.trash');
    Route::get('/brand/restore/{id}', [BrandController::class, 'restore'])->name('brand.restore');
    Route::delete('/brand/force-delete/{id}', [BrandController::class, 'forceDelete'])->name('brand.force_delete');
    Route::resource('brand', BrandController::class);
});


Route::prefix('backend')->name('backend.')->middleware('auth')->group(function () {
    Route::get('/slider/trash', [SliderController::class, 'trash'])->name('slider.trash');
    Route::get('/slider/restore/{id}', [SliderController::class, 'restore'])->name('slider.restore');
    Route::delete('/slider/force-delete/{id}', [SliderController::class, 'forceDelete'])->name('slider.force_delete');
    Route::resource('slider', SliderController::class);
});

app/Http/Controllers/Backend/AttributeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\AttributeRequest;
use App\Models\Tag;
use App\Models\Attribute;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AttributeController extends BackendBaseController
{
    protected $panel = 'Attribute';
    protected  $base_path = 'backend.attribute.';
    protected  $base_route = 'backend.attribute.';

    public function  __construct(){
        $this->model = new Attribute();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['records'] = $this->model->all();
        return view($this->__loadDataToView($this->base_path . 'index'),compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['products'] = Product::pluck('name','id');
        return view( $this->__loadDataToView($this->base_path . 'create'),compact('data'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AttributeRequest $request)
    {
        $request->request->add(['created_at' => Auth::user()->id]);
        $attribute= $this->model->create($request->all());
        if ($attribute){
            $request->session()->flash('success',$this->panel . ' created successfully');
        } else {
            $request->session()->flash('error',$this->panel . ' creation failed');
        }
        return redirect()->route($this->base_route . 'index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['record'] = $this->model->findOrFail($id);
        return  view($this->__loadDataToView($this->base_path . 'show'),compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['tags'] = Tag::pluck('name','id');
        $data['products'] = Product::pluck('name','id');
        $data['record'] = $this->model->findOrFail($id);
        return  view($this->__loadDataToView($this->base_path . 'edit'),compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AttributeRequest $request, $id)
    {
        $data['record'] = $this->model->findOrFail($id);

        $request->request->add(['updated_at' => Auth::user()->id]);

        if ($data['record']->update($request->all())){
            $request->session()->flash('success',$this->panel . ' updated successfully');
        } else {
            $request->session()->flash('error',$this->panel . ' update failed');
        }
        return redirect()->route($this->base_route . 'index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data['record'] = $this->model->findOrFail($id);
        if ($data['record']->delete()){
            request()->session()->flash('success',$this->panel . ' deleted successfully');
        } else {
            request()->session()->flash('error',$this->panel . ' delete failed');
        }
        return redirect()->route($this->base_route . 'index');
    }
    public function trash()
    {
        $data['records'] = $this->model->onlyTrashed()->get();
        return view($this->__loadDataToView($this->base_path . 'trash'),compact('data'));
    }

    public function restore($id)
    {
        $data['record'] = $this->model->onlyTrashed()->where('id',$id)->restore();
        request()->session()->flash('success',$this->panel . ' restored');

        return redirect()->route($this->base_route . 'trash');
    }

    public function forceDelete(Request  $request,$id)
    {
        $data['record'] = $this->model->onlyTrashed()->where('id',$id)->forceDelete();
        request()->session()->flash('success',$this->panel . ' deleted successfully');
        return redirect()->route($this->base_route . 'trash');
    }




}

app/Http/Controllers/Backend/BackendBaseController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendBaseController extends Controller
{
    protected  function  __loadDataToView($viewPath){
        view()->composer($viewPath, function ($view) {
            $view->with('panel', $this->panel);
            $view->with('base_path', $this->base_path);
            $view->with('base_route', $this->base_route);
        });
        return $viewPath;
    }

}

app/Http/Controllers/Backend/BrandController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\BrandRequest;
use App\Models\Brand;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Intervention\Image\Facades\Image;

class BrandController extends BackendBaseController
{
    protected $panel = 'Brand';
    protected  $base_path = 'backend.brand.';
    protected  $base_route = 'backend.brand.';

    public function  __construct(){
        $this->model = new Brand();
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['records'] = $this->model->all();
        return view($this->__loadDataToView($this->base_path . 'index'),compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view( $this->__loadDataToView($this->base_path . 'create'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BrandRequest $request)
    {
        $request->request->add(['created_by' => Auth::user()->id]);

        if ($request->hasFile('image_file'))
        {
            $image = $request->file('image_file');
            //image storage
            $image_name = uniqid() . '_' . $image->getClientOriginalName();
            $image->move('assets/images/brand/',$image_name);
            $request->request->add(['image' => $image_name]);
//image_resize
            $sizes = config('size.brand');
            $imager = Image::make('assets/images/brand/'.$image_name);

            foreach ($sizes as $size) {
                $imager->resize ($size['width'],$size['height']);
                $imager->save('assets/images/brand/'. $size['width'] . '_' . $size['height'] . '_' .$image_name);
            }
        }
        $brand = $this->model->create($request->all());
        if ($brand){
            $request->session()->flash('success',$this->panel . ' created successfully');
        } else {
            $request->session()->flash('error',$this->panel . ' creation failed');
        }
        return redirect()->route($this->base_route . 'index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data['record'] = $this->model->findOrFail($id);
        return  view($this->__loadDataToView($this->base_path . 'show'),compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['record'] = $this->model->findOrFail($id);
        return  view($this->__loadDataToView($this->base_path . 'edit'),compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(BrandRequest $request, $id)
    {
        $data['record'] = $this->model->findOrFail($id);

        $request->request->add(['updated_by' => Auth::user()->id]);

        if ($data['record']->update($request->all())){
            $request->session()->flash('success',$this->panel . ' updated successfully');
        } else {
            $request->session()->flash('error',$this->panel . ' update failed');
        }
        return redirect()->route($this->base_route . 'index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data['record'] = $this->model->findOrFail($id);
        if ($data['record']->delete()){
            request()->session()->flash('success',$this->panel . ' deleted successfully');
        } else {
            request()->session()->flash('error',$this->panel . ' delete failed');
        }
        return redirect()->route($this->base_route . 'index');
    }
    public function trash()
    {
        $data['records'] = $this->model->onlyTrashed()->get();
        return view($this->__loadDataToView($this->base_path . 'trash'),compact('data'));
    }

    public function restore($id)
    {
        $data['record'] = $this->model->onlyTrashed()->where('id',$id)->restore();
        request()->session()->flash('success',$this->panel . ' restored');

        return redirect()->route($this->base_route . 'trash');
    }

    public function forceDelete(Request  $request,$id)
    {
        $data['record'] = $this->model->onlyTrashed()->where('id',$id)->forceDelete();
        request()->session()->flash('success',$this->panel . ' deleted successfully');
        return redirect()->route($this->base_route . 'trash');
    }




}

resources/views/backend/product/create.blade.php
@extends('backend.layouts.backend')
@section('title','Create ' . $panel)
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{$panel}} Management</h1>
                    <a href="{{route($base_route . 'index')}}" class="btn btn-info">List</a>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                        <li class="breadcrumb-item" ><a href="{{route($base_route . 'index')}}">{{$panel}}</a></li>
                        <li class="breadcrumb-item active">Create</li>

                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Create {{$panel}}</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                {!! Form::open(['route' => $base_route . 'store','method' => 'post', 'enctype' => 'multipart/form-data']) !!}
                <div class="col-12 col-sm-12">
                    <div class="card card-primary card-outline card-outline-tabs">
                        <div class="card-header p-0 border-bottom-0">
                            <ul class="nav nav-tabs" id="custom-tabs-four-tab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="custom-tabs-four-basic-tab" data-toggle="pill" href="#custom-tabs-four-basic" role="tab" aria-controls="custom-tabs-four-basic" aria-selected="true">Basic Information</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="custom-tabs-four-meta-tab" data-toggle="pill" href="#custom-tabs-four-meta" role="tab" aria-controls="custom-tabs-four-meta" aria-selected="false">Meta Information</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="custom-tabs-four-tag-tab" data-toggle="pill" href="#custom-tabs-four-tag" role="tab" aria-controls="custom-tabs-four-tag" aria-selected="false">Tags</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="custom-tabs-four-attribute-tab" data-toggle="pill" href="#custom-tabs-four-attribute" role="tab" aria-controls="custom-tabs-four-attribute" aria-selected="false">Attribute</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="custom-tabs-four-image-tab" data-toggle="pill" href="#custom-tabs-four-image" role="tab" aria-controls="custom-tabs-four-image" aria-selected="false">Image</a>
                                </li>
                            </ul>
                        </div>
                        <div class="card-body">
                            <div class="tab-content" id="custom-tabs-four-tabContent">
                                <div class="tab-pane fade active show" id="custom-tabs-four-basic" role="tabpanel" aria-labelledby="custom-tabs-four-basic-tab">
                                    @include($base_path . 'includes.basic')
                                </div>
                                <div class="tab-pane fade" id="custom-tabs-four-meta" role="tabpanel" aria-labelledby="custom-tabs-four-meta-tab">
                                    @include($base_path . 'includes.meta')

                                </div>
                                <div class="tab-pane fade" id="custom-tabs-four-tag" role="tabpanel" aria-labelledby="custom-tabs-four-tag-tab">
                                    @include($base_path . 'includes.tag')

                                </div>
                                <div class="tab-pane fade" id="custom-tabs-four-attribute" role="tabpanel" aria-labelledby="custom-tabs-four-attribute-tab">
                                    @include($base_path . 'includes.attribute')

                                </div>
                                <div class="tab-pane fade" id="custom-tabs-four-image" role="tabpanel" aria-labelledby="custom-tabs-four-image-tab">
                                    @include($base_path . 'includes.image')

                                </div>
                            </div>
                        </div>
                        <!-- /.card -->
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::submit('Save Product',['class' => 'btn btn-success']) !!}
                    {!! Form::button('Reset',['type' => 'reset','class' => 'btn btn-danger']); !!}
                </div>


                {!! Form::close() !!}
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                Footer
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
@endsection
@section('js')
    <script>
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        $('#category_id').change(function (){
            var category_id = $(this).val();
            $.ajax({
                url:"{{route('backend.category.get_subcategory')}}",
                method:'post',
                data:{'cid' : category_id},
                success:function (response){
                    $('#subcategory_id').html(response);
                }
            });
        });
    </script>
    <script>
        var attribute_wrapper = $("#attribute_wrapper"); //Fields wrapper
        var add_button_attribute = $("#addMoreAttribute"); //Add button ID
        var y = 1;
        $(add_button_attribute).click(function (e) { //on add input button click
            e.preventDefault();
            var max_fields = 5; //maximum input boxes allowed
            if (y < max_fields) { //max input box allowed
                y++; //text box increment
                //add new row
                $("#attribute_wrapper tr:last").after(
                    '<tr>'+
                    '   <td>{!! Form::select('attribute_id[]',$data['attributes'],null,['class' => 'form-control','placeholder' => "Select Attribute"]) !!}'+
                    '   </td>'+
                    '   <td><input type="text" name="attribute_value[]" class="form-control" placeholder="Enter Attribute Value"/></td>'+
                    '   <td>'+
                    '       <a class="btn btn-block btn-warning sa-warning remove_row"><i class="fa fa-trash"></i></a>'+
                    '   </td>'+
                    '</tr>'
                );
            }else{
                alert('Maximum Attribute Limit is 5');
            }
        });
        //remove row
        $(attribute_wrapper).on("click", ".remove_row", function (e) {
            e.preventDefault();
            $(this).parents("tr").remove();
            y--;
        });
    </script>

    <script>
        var image_wrapper = $("#image_wrapper"); //Fields wrapper
        var add_button_image = $("#addMoreImage"); //Add button ID
        var x = 1;
        $(add_button_image).click(function (e) { //on add input button click
            e.preventDefault();
            var max_fields = 5; //maximum input boxes allowed
            if (x < max_fields) { //max input box allowed
                x++; //text box increment
                //add new row
                $("#image_wrapper tr:last").after(
                    '<tr>'+
                    '   <td> {!!  Form::file('image_file[]', null,['class' => 'form-control'])!!}'+
                    '   </td>'+
                    '   <td><input type="text" name="image_title[]" class="form-control" placeholder="Enter image_title Value"/></td>'+
                    '   <td>'+
                    '       <a class="btn btn-block btn-warning sa-warning remove_row"><i class="fa fa-trash"></i></a>'+
                    '   </td>'+
                    '</tr>'
                );
            }else{
                alert('Maximum Image Limit is 5');
            }
        });
        //remove row
        $(image_wrapper).on("click", ".remove_row", function (e) {
            e.preventDefault();
            $(this).parents("tr").remove();
            x--;
        });
    </script>
@endsection

resources/views/backend/product/index.blade.php
@extends('backend.layouts.backend')
@section('title','List ' . $panel)
@section('main-content')
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>{{$panel}} Management</h1>
                    <a href="{{route($base_route . 'create')}}" class="btn btn-info">Create</a>
                    <a href="{{route($base_route . 'trash')}}" class="btn btn-danger">Trash</a>

                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                        <li class="breadcrumb-item" ><a href="{{route($base_route . 'index')}}">{{$panel}}</a></li>
                        <li class="breadcrumb-item active"><a href="{{route('home')}}">Home</a></li>

                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">List {{$panel}}</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body">
                @if(session('success'))
                    <div class="alert alert-success">{{session('success')}}</div>
                @endif
                @if(session('error'))
                    <div class="alert alert-danger">{{session('error')}}</div>
                @endif
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>SN</th>
                        <th>Category</th>
                        <th>SubCategory</th>
                        <th>Name</th>
                        <th>Slug</th>
                        <th>Stock</th>
                        <th>Quantity</th>
                        <th>Created At</th>
                        <th>Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach($data['records'] as $record)
                        <tr>
                            <td>{{$loop->index+1}}</td>
                            <td>@if($record->category_id)
                                    {{$record->category->name}}
                                @endif</td>
                            <td>@if($record->subcategory_id)
                                    {{$record->subcategory->name}}
                                @endif</td>
                            <td>{{$record->name}}</td>
                            <td>{{$record->slug}}</td>
                            <td>{{$record->stock}}</td>
                            <td>{{$record->quantity}}</td>
                            <td>{{$record->created_at}}</td>
                            <td>
                                <a href="{{route($base_route . 'show',$record->id)}}" class="btn btn-info">View</a>
                                <a href="{{route($base_route .'edit',$record->id)}}" class="btn btn-warning">Edit</a>
                                {!! Form::open(['route' => [$base_route .'destroy', $record->id],'method' => 'delete']) !!}
                                {!! Form::submit('Delete',['class' => 'btn btn-danger']) !!}
                                {!! Form::close() !!}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                Footer
            </div>
            <!-- /.card-footer-->
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
@endsection